version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
      "postgres/master/Dockerfile",
      "postgres/slave/Dockerfile",
      "mysql/master/Dockerfile",
      "mysql/slave/Dockerfile",
  ]
