version: "3.8"

networks:
    mysql-replication:
        driver: bridge

volumes:
    master-data:
    slave-data:

services:
    mysql-master:
        container_name: mysql-master
        image: mysql-master
        restart: always
        networks:
            - mysql-replication
        ports:
            - 4306:3306
        volumes:
            - master-data:/var/lib/mysql
        build:
            context: ./master
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_DATABASE: mysql
            POSTGRES_REPLICATION_USER: replica
            POSTGRES_REPLICATION_PASSWORD: strongpassword

#     postgres-slave:
#         container_name: postgres-slave
#         image: postgres-slave
#         restart: always
#         networks:
#             - postgres-replication
#         ports:
#             - 6532:5432
#         volumes:
#             - slave-data:/var/lib/postgresql/data
#         build:
#             context: ./slave
#         environment:
#             POSTGRES_PASSWORD: password
#             POSTGRES_USER: user
#             POSTGRES_DATABASE: postgres
#             POSTGRES_REPLICATION_USER: replica
#             POSTGRES_REPLICATION_PASSWORD: strongpassword
