version: "3.8"

networks:
    mysql-replication:
        driver: bridge

volumes:
    master-data:
    slave-data:

services:
    mysql-master:
        container_name: mysql-master
        image: mysql-master
        restart: always
        networks:
            - mysql-replication
        ports:
            - 4306:3306
        volumes:
            - master-data:/var/lib/mysql
        build:
            context: ./master
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_DATABASE: mysql

    # mysql-slave:
    #     container_name: mysql-slave
    #     image: mysql-slave
    #     restart: always
    #     networks:
    #         - mysql-replication
    #     ports:
    #         - 4406:5432
    #     volumes:
    #         - slave-data:/var/lib/mysql
    #     build:
    #         context: ./slave
    #     environment:
    #         MYSQL_ROOT_PASSWORD: rootpassword
    #         MYSQL_PASSWORD: password
    #         MYSQL_USER: user
    #         MYSQL_DATABASE: mysql
